data_dir: /m/cs/scratch/csb/projects/enhancer_prediction/aaltorse/Data
#data_dir: /u/45/vanvlm1/unix/scratch_cs/csb/projects/enhancer_prediction/aaltorse/Data
cell_line: K562 

# Configuration for extract_enhancers
extract_enhancers:
  window: 2000          # Profile window size
  binSize: 100          # Resolution of the data
  N: 1000               # Number of trainind data enhancers to extract
  distToPromotor: 2000  # Maximum distance to nearest promotor
