channels:
  - conda-forge
  - bioconda

dependencies:
  # For preprocessing pipeline
  - r-base > 3.5, < 4.0
  - bowtie2
  - samtools
  - bedtools
  - phantompeakqualtools
  - bioconductor-rsamtools
  - bioconductor-genomeinfodb
  - bioconductor-genomeinfodbdata
  - snakemake
  - pandas
  # - r-gdata
  # - r-circlize
  # - r-doParallel
  # - r-ggplot2
  # - r-GetoptLong
  # - r-gridExtra
  # - r-pryr
  # - r-reshape2
  # - r-ROCR
  # - bioconductor-ShortRead

  # For train-predict
  - bioconductor-bsgenome.hsapiens.ucsc.hg19
  - r-optparse
  - r-doparallel
  - r-gdata
  - r-mass
  - gnuplot
  - libsvm
